name: Install Repo
description: Install the toolchain and dependencies

inputs:
  ts:
    description: Whether to install Node.js and dependencies
    required: true
    default: "true"
  python:
    description: Whether to install Python and dependencies
    required: false
    default: "false"

runs:
  using: "composite"

  steps:
    - name: Set up bun
      uses: oven-sh/setup-bun@v1
      if: ${{ inputs.ts == 'true' }}
      with:
        version: 1.2.11
        run_install: true

    - uses: actions/setup-python@v5
      if: ${{ inputs.python == 'true' }}
      with:
        python-version: "3.11"
        architecture: "x64"
        cache: 'pip'

    - name: Install dependencies
      if: ${{ inputs.ts == 'true' }}
      shell: bash
      run: |
        bun install --recursive
